version: '3'
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
        depends_on:
            - api
            - client
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    api:
        depends_on:
            - postgres
            - redis
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /usr/app/node_modules
            - ./server:/usr/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /usr/app/node_modules
            - ./client:/usr/app           
    worker:
        depends_on: 
            - redis
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /usr/app/node_modules
            - ./worker:/usr/app   
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379            